# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-02 07:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0002_auto_20170402_0236'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensaje',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
