# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-06 05:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
