# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-28 03:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numid', models.CharField(max_length=15)),
                ('nombre', models.CharField(max_length=40)),
                ('apellido', models.CharField(max_length=40)),
                ('direccion', models.CharField(max_length=100)),
                ('telefono_f', models.CharField(max_length=9)),
                ('telefono_c', models.CharField(max_length=9)),
                ('activo', models.BooleanField(default=True)),
                ('correo', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Anio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateTimeField()),
                ('fin', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Clase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clase', models.CharField(max_length=30)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Configuracion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=15)),
                ('direccion', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=9)),
                ('indice', models.IntegerField()),
                ('logo', models.ImageField(upload_to='media/logo')),
                ('nombredirector', models.CharField(blank=True, max_length=50, null=True)),
                ('telefonod', models.CharField(blank=True, max_length=9, null=True)),
                ('anioactual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admini.Anio')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleMatricula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota1', models.PositiveSmallIntegerField(default=0)),
                ('nota2', models.PositiveSmallIntegerField(default=0)),
                ('nota3', models.PositiveSmallIntegerField(default=0)),
                ('nota4', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='EncargadoAlumno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admini.Alumno')),
            ],
        ),
        migrations.CreateModel(
            name='EstadoAlumno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=15)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoClase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Grado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grado', models.CharField(max_length=15)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='GradoClase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admini.Clase')),
                ('grado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admini.Grado')),
            ],
        ),
        migrations.CreateModel(
            name='GradoSeccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('grado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admini.Grado')),
            ],
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admini.Alumno')),
            ],
        ),
        migrations.CreateModel(
            name='OfertaClase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='OfertaGrado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacidad', models.IntegerField()),
                ('disponibles', models.IntegerField()),
                ('anio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admini.Anio')),
                ('gradoseccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admini.GradoSeccion')),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numid', models.CharField(max_length=15)),
                ('direccion', models.CharField(max_length=100)),
                ('telefono_f', models.CharField(blank=True, max_length=9, null=True)),
                ('telefono_c', models.CharField(blank=True, max_length=9, null=True)),
                ('es_admin', models.BooleanField(default=False)),
                ('es_secre', models.BooleanField(default=False)),
                ('es_docente', models.BooleanField(default=False)),
                ('es_tutor', models.BooleanField(default=False)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Seccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seccion', models.CharField(max_length=15)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sexo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sexo', models.CharField(max_length=9)),
            ],
        ),
        migrations.AddField(
            model_name='ofertaclase',
            name='docente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admini.Perfil'),
        ),
        migrations.AddField(
            model_name='ofertaclase',
            name='gradoclase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admini.GradoClase'),
        ),
        migrations.AddField(
            model_name='ofertaclase',
            name='ofertagrado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admini.OfertaGrado'),
        ),
        migrations.AddField(
            model_name='matricula',
            name='ofertagrado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admini.OfertaGrado'),
        ),
        migrations.AddField(
            model_name='gradoseccion',
            name='seccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admini.Seccion'),
        ),
        migrations.AddField(
            model_name='encargadoalumno',
            name='encargado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admini.Perfil'),
        ),
        migrations.AddField(
            model_name='detallematricula',
            name='estadoclase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admini.EstadoClase'),
        ),
        migrations.AddField(
            model_name='detallematricula',
            name='matricula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admini.Matricula'),
        ),
        migrations.AddField(
            model_name='detallematricula',
            name='ofertaclase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admini.OfertaClase'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='estadoalumno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admini.EstadoAlumno'),
        ),
        migrations.AlterUniqueTogether(
            name='ofertagrado',
            unique_together=set([('gradoseccion', 'anio')]),
        ),
        migrations.AlterUniqueTogether(
            name='ofertaclase',
            unique_together=set([('gradoclase', 'ofertagrado', 'docente')]),
        ),
        migrations.AlterUniqueTogether(
            name='matricula',
            unique_together=set([('alumno', 'ofertagrado')]),
        ),
        migrations.AlterUniqueTogether(
            name='gradoseccion',
            unique_together=set([('grado', 'seccion')]),
        ),
        migrations.AlterUniqueTogether(
            name='gradoclase',
            unique_together=set([('grado', 'clase')]),
        ),
        migrations.AlterUniqueTogether(
            name='encargadoalumno',
            unique_together=set([('encargado', 'alumno')]),
        ),
        migrations.AlterUniqueTogether(
            name='detallematricula',
            unique_together=set([('matricula', 'ofertaclase')]),
        ),
    ]
