# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-28 05:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admini', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Perfil', to=settings.AUTH_USER_MODEL),
        ),
    ]
