# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-30 21:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admini', '0002_auto_20170328_0024'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='sexo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admini.Sexo'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='sexo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admini.Sexo'),
        ),
        migrations.AlterField(
            model_name='anio',
            name='fin',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='anio',
            name='inicio',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='encargadoalumno',
            name='encargado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='ofertaclase',
            name='docente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
