# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-31 15:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admini', '0003_auto_20170330_1521'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ofertagrado',
            old_name='capacidad',
            new_name='cupos',
        ),
        migrations.RemoveField(
            model_name='ofertagrado',
            name='disponibles',
        ),
    ]
